# Generated by Django 4.0.5 on 2022-06-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_user', models.CharField(max_length=255)),
                ('first_name_user', models.CharField(max_length=255)),
                ('last_name_user', models.CharField(max_length=255)),
                ('date_create_user', models.DateField(auto_now_add=True)),
                ('photo_profile_user', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('email_user', models.EmailField(max_length=255)),
            ],
        ),
    ]
