# Generated by Django 4.0.5 on 2022-06-24 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tetapp', '0002_category_posts_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Category', 'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['time_create', 'title'], 'verbose_name': 'Post', 'verbose_name_plural': 'Post'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tetapp.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.TextField(blank=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Create'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Update'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
